### ISSUE TITLE
Update the instructions to train a classifier using csv instead of json

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/questions-with-classifier-ega#1]
The [Stage 4](https://github.com/watson-developer-cloud/questions-with-classifier-ega#stage-4-train-the-classifier) requires users to train a classifier using `json` but the service doesn't support it at the moment. We need to update the instructions to use `csv`.

**Comment by tdalbo92** [comment]
We noticed that now.  We were hoping the Classifier team would keep their Beta APIs as promised, but they removed support for that. We're working on it now.
