### ISSUE TITLE
Dead link for API reference

### ISSUE THREAD

**Issue by tdalbo92** [watson-developer-cloud/questions-with-classifier-ega#10]
Ask "What is the API?" and click the link.  The page will redirect to a GET error, and a blank page.

**Comment by bsfarrell** [comment]
The answer class is api_documentation.

The following answer classes also have broken links:

classifier_documentation
deployed_in_bluemix
how_to_train
how_to_use
response_to_classify

All point to somewhere in https://watson.mybluemix.net

**Comment by bsfarrell** [comment]
Also integrate_other_services

**Comment by bsfarrell** [comment]
I fixed classifier_documentation and integrate_other_services in production via the manage api, fyi.

**Comment by bsfarrell** [comment]
Closed by pull request #23
