### ISSUE TITLE
Powered By should be a link

### ISSUE THREAD

**Issue by sroorda** [watson-developer-cloud/questions-with-classifier-ega#13]
We should turn the 'Powered By IBM Watson Natural Language Clsasifier' into a link.  This link should take you to the main documentation page for the classifier service.

**Comment by tdalbo92** [comment]
Does the gallery application page have a link to the classifier documentation?  That might be a "two birds one stone" approach, if they can get to the github code *and* get to the classifier service docs from one place.

**Comment by sroorda** [comment]
It does but isn't it strange to have a circular link like that?

Stephan Roorda
Senior Cognitive Software Engineer
Watson Engagement Advisor - Algorithms
(919) 486-0882

Work to Live, Don't Live to Work

**Comment by bvonhag** [comment]
The NLC engagement gallery application's entry has a link to the 
documentation for that application. The docs for that application do not 
have a link to the primary NL Classifier documentation, though that's a 
good idea.

I'm not sure what you mean by a circular link?

   Bill

Bill von Hagen
Watson Platform Developer Content and Community Manager
IBM Watson Group
email: bvonhag@us.ibm.com | Tel: 412-315-2134
Participant Code for calls: 98397956

**Comment by tdalbo92** [comment]
It's not circular if they're coming from our app, not from our github.  We can't assume every person using the app has built and deployed it from github.
 
----- Original message -----From: Stephan J Roorda <notifications@github.com>To: watson-developer-cloud/questions-with-classifier-ega <questions-with-classifier-ega@noreply.github.com>Cc: Thomas N Dalbo1/Boston/IBM@IBMUSSubject: Re: [questions-with-classifier-ega] Powered By should be a link (#13)Date: Mon, Aug 17, 2015 12:05 PM It does but isn't it strange to have a circular link like that?Stephan RoordaSenior Cognitive Software EngineerWatson Engagement Advisor - Algorithms(919) 486-0882Work to Live, Don't Live to WorkFrom: Tom Dalbo <notifications@github.com>To: watson-developer-cloud/questions-with-classifier-ega<questions-with-classifier-ega@noreply.github.com>Cc: Stephan J Roorda/Raleigh/IBM@IBMUSDate: 08/17/2015 12:00 PMSubject: Re: [questions-with-classifier-ega] Powered By should be a link(#13)Does the gallery application page have a link to the classifierdocumentation? That might be a "two birds one stone" approach, if they canget to the github code and get to the classifier service docs from oneplace.—Reply to this email directly or view it on GitHub.

**Comment by sroorda** [comment]
The link says "Powered By Natural Language Classifier" it should take us to a page about the Natural Language Classifier.  Unless there is a better choice it should be the main documentation page for the Natural Language Classifier.  It would be confusing to go to the gallery for the app when clicking that link.

**Comment by tdalbo92** [comment]
I think the original feature request was to have a way to get our source code from the application, but I see how that link wouldn't make sense hidden behind the Powered By text.
