### ISSUE TITLE
Investigate adding a 'Deploy to BlueMix' button to documentation

### ISSUE THREAD

**Issue by sroorda** [watson-developer-cloud/questions-with-classifier-ega#15]
We need to investigate if we can add a deploy to bluemix button.  I looked at this previously and should have most of the work already done.  It just requires a github url and a yaml file.

This would also require a doc update because it would replace the manual steps to deploy the app.

Being reliant on the common/framework repository might be an issue here.

**Comment by bsfarrell** [comment]
There's a clickable Bluemix button in the pull request you can try.

What do you think- should we update the doc to replace all of stages 1 and 2 with a Bluemix button?

**Comment by sroorda** [comment]
Looks good and it worked for me.  It did take several minutes (at least 5).  I had this working at 1 point as well but never was able to test end to end without being in github (which we are now).

I would suggest that we move the current instructions for #1 to another section.  "If you want to clone this yourself" or something like that.  Then we can replace with the button.

I would also suggest adding a few "notes":
  1 - you will need to sign up or login to your bluemix account
  2 - it will take several minutes 
  3 - the app will not work unless you complete the rest of the instructions

**Comment by bsfarrell** [comment]
Addressed doc updates in pull request #18
