### ISSUE TITLE
Improper handing of multi-byte characters in user tracking logger

### ISSUE THREAD

**Issue by bsfarrell** [watson-developer-cloud/questions-with-classifier-ega#51]
We set a column size of 1024 bytes, and truncate the impression prompt field to 1024 characters.  But 1024 characters != 1024 bytes.

**Comment by tdalbo92** [comment]
I guess we'll have to truncate to 512 characters?

**Comment by bsfarrell** [comment]
Believe this solution should be sufficient.

int maxLen = DB_FIELD_LENGTH-2;
string = new String( string.getBytes("UTF-8") , 0, maxLen, "UTF-8");

https://theholyjava.wordpress.com/2007/11/02/truncating-utf-string-to-the-given/
