### ISSUE TITLE
mvn package not working

### ISSUE THREAD

**Issue by FWMatt** [watson-developer-cloud/questions-with-classifier-ega#52]
Hi,

I'm running through the tutorial instructions, but can't build the repo.

```mvn package```

Gives me

```[ERROR] Failed to execute goal on project questions-with-classifier-ega-war: Could not resolve dependencies for project com.ibm.watson.app.gallery:questions-with-classifier-ega-war:war:1.0.2-SNAPSHOT: The following artifacts could not be resolved: com.ibm.watson.app.gallery:framework-ega-infra:jar:1.0.2-SNAPSHOT, com.ibm.watson.app.gallery:framework-ega-infra:jar:tests:1.0.2-SNAPSHOT, com.ibm.watson.app.gallery:framework-ega-test:jar:1.0.2-SNAPSHOT: Could not find artifact com.ibm.watson.app.gallery:framework-ega-infra:jar:1.0.2-SNAPSHOT -> [Help 1]```

Any ideas on how to resolve this please?

Thank you
Matt

**Comment by bsfarrell** [comment]
See this step.  You need to clone and install the framework-ega project.  Once you do that, `mvn package` should work.

https://github.com/watson-developer-cloud/questions-with-classifier-ega#cloning-and-building-the-project-yourself

**Comment by FWMatt** [comment]
Ah - thanks. I tried the "Deploy to Bluemix" approach initially.

I've built the framework-ega repo, now I'm trying to build the questions-with-classifier-ega repo. I get the following error:

```[ERROR] Plugin net.wasdev.wlp.maven.plugins:liberty-maven-plugin:1.1-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact net.wasdev.wlp.maven.plugins:liberty-maven-plugin:jar:1.1-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]```

Thanks again for your help.

**Comment by tdalbo92** [comment]
Looks like @bsfarrell has a fix in the works for that.  You should be un-broken shortly.

**Comment by bsfarrell** [comment]
Just pushed a fix.  Pull the latest and you should be set.

**Comment by FWMatt** [comment]
Thanks for the help so far - that fixed the build.

I'm now running through the documentation. Two suggestions

1. It would probably useful if the documentation gave the relative path for the questions file from the root of the app to stop people from having to search for them.

```curl -u <username>:<password> -F training_data=@<put questions.cv relative path here> -F training_metadata="{\"language\":\"en\",\"name\":\"my_classifier\"}" "https://<url>/v1/classifiers"```

2. The manifest.yml appears to require services to be called question-classifier and question-db. The documentation should probably suggest you call the services these names

I've now got my app created. I called the services something different to begin with, then renamed them. I now get the following log:

```Uploading fwqaclassifier...
Uploading app files from: questions-with-classifier-ega-war/target/questions-with-classifier-ega-war.war
Uploading 1.9M, 226 files
Done uploading               
OK
FAILED
Could not find service questions-classifier to bind to fwqaclassifier```

I do have ```questions-classifier``` service. Any ideas on what is causing this issue?

Thanks again
