### ISSUE TITLE
Display error execute curl -X POST

### ISSUE THREAD

**Issue by acastillo2015** [watson-developer-cloud/questions-with-classifier-ega#55]
I have problem when I run this command:

curl -X POST -H "Content-Type: application/json" -d @questions-with-classifier-ega-war\target\classes/answers.json
http://buscadorinteligente.mybluemix.net/api/v1/manage/answer

Display this error:
Exception thrown by application class 'com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.createSingletonInstance:220'
javax.servlet.ServletException: Resource class com.ibm.watson.app.qaclassifier.ClassifierApplicationImpl can not be instantiated due to InvocationTargetException
at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.createSingletonInstance(LibertyJaxRsServerFactoryBean.java:220)
at [internal classes]
at com.ibm.watson.app.common.util.rest.CORSFilter.doFilter(CORSFilter.java:38)
at com.ibm.ws.webcontainer.filter.FilterInstanceWra pper.doFilter(FilterInstanceWrapper.java:207)
at [internal classes]

**Comment by tdalbo92** [comment]
I'm looking into it now - I'll update you with what I find.

**Comment by tdalbo92** [comment]
Sorry for the delay.  When following these instructions, you're building the code with maven and deploying it yourself with the `cf` command line utility?

**Comment by acastillo2015** [comment]
Team,

Yes, I am following step by step deploy  with this:


   1.	Clone the framework-ega repository by issuing one of the following
      commands:


       git clone
      https://github.com/watson-developer-cloud/framework-ega.git

       git clone git@github.com:watson-developer-cloud/framework-ega.git

   2.	Run mvn install in the root of the framework-ega repository to build
      and install the components to your local Maven repository.
   3.	Clone the questions-with-classifier-ega repository by issuing one of
      the following commands:


       git clone
      https://github.com/watson-developer-cloud/questions-with-classifier-ega.git


       git clone
      git@github.com:watson-developer-cloud/questions-with-classifier-ega.git


   4.	Run mvn install in the root of the questions-with-classifier-ega
      repository to build and install the components to your local Maven
      repository.


      The questions-with-classifier-ega-war.war file is in the
      /questions-with-classifier-ega/questions-with-classifier-ega-war/target
       directory.


Saludos y bendiciones/Regards and blessings,

Armando Jose Castillo Espinoza
IBM Cloud Platform Services for Latin America - Bluemix
IBM Bluemix™ Team
                                                                                                                            
                                                                                                                            
                                                                                                                            
 Phone: 56-2-200-3675 | Mobile: 56-9-9543-4671                                                                          IBM 
 E-mail: acastillo@cl.ibm.com                                                                                               
 Chat: Sametime: acastillo@cl.ibm.com Skype: armandojc2006 Google Talk: castillo.armando                Av. Providencia 655 
 Find me on: LinkedIn:                                                                       Santiago De Chile, RM 750-0261 
 https://www.linkedin.com/profile/public-profile-settings?trk=prof-edit-edit-public_profile                           Chile 
 Twitter: ajcastilloe                                                                                                       
                                                                                                                            





From:	Tom Dalbo <notifications@github.com>
To:	watson-developer-cloud/questions-with-classifier-ega
            <questions-with-classifier-ega@noreply.github.com>
Cc:	Armando Jose Castillo Espinoza/Chile/IBM@IBMCL
Date:	17-12-2015 10:38
Subject:	Re: [questions-with-classifier-ega] Display error execute curl
            -X POST (#55)



Sorry for the delay. When following these instructions, you're building the
code with maven and deploying it yourself with the cf command line utility?


—
Reply to this email directly or view it on GitHub.

**Comment by tdalbo92** [comment]
Then afterwards, you're sure all the proper services have been manually created and bound to the application you've created in Bluemix?

Once you run `cf push` the application will be able to take connections for uploading to the answer store.

**Comment by acastillo2015** [comment]
Saludos y bendiciones/Regards and blessings,

Armando Jose Castillo Espinoza
IBM Cloud Platform Services for Latin America - Bluemix
IBM Bluemix™ Team
                                                                                                                            
                                                                                                                            
                                                                                                                            
 Phone: 56-2-200-3675 | Mobile: 56-9-9543-4671                                                                          IBM 
 E-mail: acastillo@cl.ibm.com                                                                                               
 Chat: Sametime: acastillo@cl.ibm.com Skype: armandojc2006 Google Talk: castillo.armando                Av. Providencia 655 
 Find me on: LinkedIn:                                                                       Santiago De Chile, RM 750-0261 
 https://www.linkedin.com/profile/public-profile-settings?trk=prof-edit-edit-public_profile                           Chile 
 Twitter: ajcastilloe                                                                                                       
                                                                                                                            





From:	Tom Dalbo <notifications@github.com>
To:	watson-developer-cloud/questions-with-classifier-ega
            <questions-with-classifier-ega@noreply.github.com>
Cc:	Armando Jose Castillo Espinoza/Chile/IBM@IBMCL
Date:	17-12-2015 11:58
Subject:	Re: [questions-with-classifier-ega] Display error execute curl
            -X POST (#55)



Then afterwards, you're sure all the proper services have been manually
created and bound to the application you've created in Bluemix?


Once you run cf push the application will be able to take connections for
uploading to the answer store.


—
Reply to this email directly or view it on GitHub.

**Comment by acastillo2015** [comment]
Saludos y bendiciones/Regards and blessings,

Armando Jose Castillo Espinoza
IBM Cloud Platform Services for Latin America - Bluemix
IBM Bluemix™ Team
                                                                                                                            
                                                                                                                            
                                                                                                                            
 Phone: 56-2-200-3675 | Mobile: 56-9-9543-4671                                                                          IBM 
 E-mail: acastillo@cl.ibm.com                                                                                               
 Chat: Sametime: acastillo@cl.ibm.com Skype: armandojc2006 Google Talk: castillo.armando                Av. Providencia 655 
 Find me on: LinkedIn:                                                                       Santiago De Chile, RM 750-0261 
 https://www.linkedin.com/profile/public-profile-settings?trk=prof-edit-edit-public_profile                           Chile 
 Twitter: ajcastilloe                                                                                                       
                                                                                                                            





From:	Tom Dalbo <notifications@github.com>
To:	watson-developer-cloud/questions-with-classifier-ega
            <questions-with-classifier-ega@noreply.github.com>
Cc:	Armando Jose Castillo Espinoza/Chile/IBM@IBMCL
Date:	17-12-2015 11:58
Subject:	Re: [questions-with-classifier-ega] Display error execute curl
            -X POST (#55)



Then afterwards, you're sure all the proper services have been manually
created and bound to the application you've created in Bluemix?


Once you run cf push the application will be able to take connections for
uploading to the answer store.


—
Reply to this email directly or view it on GitHub.

**Comment by tdalbo92** [comment]
Both of those messages seem to be blank.  

My suggestion if you're still having problems is to start from scratch.  Delete the application on Bluemix and any services bound to it (as long as they're not shared with other people, of course).  Then follow the instructions from step 1 with a freshly cloned repository on your computer, and we'll see if these problems come back again.

**Comment by acastillo2015** [comment]
When I execute this step:

 Run mvn install in the root of the questions-with-classifier-ega repository to build and install the components to your local Maven repository.

Display this information:

[INFO] Reactor Summary:
[INFO]
[INFO] questions-with-classifier-ega ...................... SUCCESS [  0.389 s]
[INFO] questions-with-classifier-ega-war .................. SUCCESS [11:48 min]
[INFO] questions-with-classifier-ega-test ................. FAILURE [ 15.359 s]

**Comment by tdalbo92** [comment]
That is okay - our tests fail due to an upstream change by the Liberty team, but that isn't affecting the problems you're having.  You can pull the repository for the updated changes - I just pushed a fix for that.

I'd look closer at verifying all the services are bound correctly to your application in Bluemix.  The most sure-fire way to do that is to delete the services and your application in bluemix, as described in the [README](https://github.com/watson-developer-cloud/questions-with-classifier-ega/blob/master/README.md#manually-creating-bluemix-services-and-deploying-to-bluemix)

**Comment by acastillo2015** [comment]
Now, display other issues...when I execute the command:

curl -X POST -H "Content-Type: application/json" -d @questions-with-classifier-ega-war\target\classes/answers.json http://finderintelligentch.mybluemix.net/api/v1/manage/answer

![issue](https://cloud.githubusercontent.com/assets/16311742/11877525/9ebb0974-a4ce-11e5-91a8-68d6e85c84a1.png)

**Comment by tdalbo92** [comment]
It looks like you're putting a forward slash right before "answers.json", but you're in Windows so it should be a backslash.

**Comment by acastillo2015** [comment]
I modify and continue a same issue:
![issue2](https://cloud.githubusercontent.com/assets/16311742/11878409/62ffc004-a4d4-11e5-8904-85901e102478.png)

**Comment by tdalbo92** [comment]
http://finderintelligentch.mybluemix.net/api/doc/#!/Manage/createAnswer

Try copy and pasting the contents of that answers.json file directly into this box, and press "try it out!" below it.  

If that isn't working for you still, I suggest running the `cf push` command, but use the .zip file instead of the .war.  You'll have to follow [these instructions](https://github.com/watson-developer-cloud/questions-with-classifier-ega/blob/master/README.md#deploying-with-security)

**Comment by acastillo2015** [comment]
Not working both options...

**Comment by tdalbo92** [comment]
You have to make sure you set the MANAGE_API_PASSWORD environment variable in the Bluemix dashboard.  That's set, and you can access the link I posted last?

If you can access the link, paste the contents of answers.json into the input on that webpage, and it still fails then it must be an issue with binding the proper Bluemix services.

**Comment by acastillo2015** [comment]
I apply all changes but display all answer "blank"

**Comment by tdalbo92** [comment]
When you press the button on this API endpoint: http://buscadorch.mybluemix.net/api/doc/#!/Manage/getAnswers do you see the answers you've generated?  If not, the answer upload process still isn't being done properly and I'd recommend you copy & paste your answers into the /manage/answer POST area and try again.

If that still isn't working, then it *must* be an issue with your classifier or with binding the proper services in Bluemix to this application.

**Comment by acastillo2015** [comment]
I deleted app...Try again from 1 step:

but when I execute http://buscadorch.mybluemix.net/api/doc/#!/Manage/getAnswers:

![answer](https://cloud.githubusercontent.com/assets/16311742/11939143/bc2f5aae-a7fe-11e5-94bc-17935906ed12.png)

I also configured MANAGE_API_PASSWORD

**Comment by tdalbo92** [comment]
Great!  So, enter in "apiuser" and use the password you have set in that environment variable, and it should return with a status 200.  

If not, try restarting your app in bluemix.  It's possible that the MANAGE_API_PASSWORD env variable hasn't been picked up by the application.

**Comment by acastillo2015** [comment]
When I run http://busca.mybluemix.net/api/doc/#!/Manage/getAnswers   return with a status 200 but body in blank

![getanswers](https://cloud.githubusercontent.com/assets/16311742/11945355/b908db46-a82d-11e5-8e6b-9a46886b9344.png)

and display the  page with answer:
![pageanswer](https://cloud.githubusercontent.com/assets/16311742/11945409/6d29ac4a-a82e-11e5-990a-6c8093440645.png)

**Comment by tdalbo92** [comment]
What's the result when you copy & paste your answers.json contents and execute the POST command on the /getAnswers operation?  Does it also return a status 200?

**Comment by acastillo2015** [comment]
![getanswer](https://cloud.githubusercontent.com/assets/16311742/11960398/39b363be-a8b1-11e5-9f88-bb76457535d3.png)

**Comment by tdalbo92** [comment]
It looks okay!  You're still not seeing answers?

**Comment by acastillo2015** [comment]
It´s Ready.. 


Thanks you Tom

**Comment by tdalbo92** [comment]
No problem
