### ISSUE TITLE
bowre install error

### ISSUE THREAD

**Issue by nishinair123** [watson-developer-cloud/questions-with-classifier-ega#56]
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:
bower (bower install) on project questions-with-classifier-ega-war: Failed to ru
n task: 'bower install' failed. (error code 1) -> [Help 1]

I got an error like  this while running MVN install command as per the tutorial.Could you suggest what the issue could be ?

**Comment by nishinair123** [comment]
this is resolved now

**Comment by tdalbo92** [comment]
Probably a timeout or a webpage being down upstream.  Glad to know it's back working!
