### ISSUE TITLE
IBM Watson Questions with Classifier- loads application but I can't see the code, help please

### ISSUE THREAD

**Issue by JFerguson576** [watson-developer-cloud/questions-with-classifier-ega#57]
I have worked through the steps on this link successfully and I can see the test application running. https://github.com/watson-developer-cloud/questions-with-classifier-ega 
Test app is:
 electricityadvisor.mybluemix.net

However, when I set up the GIT repo and then start to edit the code, I only see the JAVA HELLO World code. I know I must be doing something wrong but I have followed the instructions to the letter and I've gone through the process over 10 times. Any help would be appreciated.

Regards, John

**Comment by tdalbo92** [comment]
Hey!

I'll need more details on the exact steps you're taking to check out and modify this code.  If you aren't familiar with git, I can provide some documentation to help you out!

**Comment by JFerguson576** [comment]
Thanks for responding. 

I didn't modify any code yet. 

I followed all the steps and then went to "Start Coding" and added "GIT" the instruction say to use the "Starter Application Code" which I did. I thought after doing the command:
cf push Powerman -p questions-with-classifier-ega-war.war
powerman.mybluemix.net 
that I would see the code in the editor and then would create the GIT from there...
Here is the GIT repo that was  created..
https://hub.jazz.net/project/zippy576/Powerman%201/overview

We are learning Bluemix and the Watson services as fast as we can. We have numerous prospects that are extremely excited about the Use Cases we are presenting so we appreciate your help.

Regards,

John

**Comment by tdalbo92** [comment]
you should be able to do this:

`git clone https://github.com/watson-developer-cloud/questions-with-classifier-ega.git`

And then see the code in that repository.  Is there an issue with git that isn't allowing you to clone it into your local workspace?

**Comment by tdalbo92** [comment]
I also want to remind you, as well as anybody watching, that this application is really meant for demo purposes only and is no longer actively developed, maintained, nor supported.  

But I'm more than happy to help with deployment questions like this.

**Comment by JFerguson576** [comment]
Thank you. I have resolved my GIT issues. We understand it is a demo but it we see it as a useful tool to learn the power of the Classifier and to engage with prospects across verticals. Is there work happening on other tools for the Classifier to create Question/Answer solutions in the pipeline?

**Comment by tdalbo92** [comment]
That'd be a question for the tooling team, as it's not directly related to the product.  

Work is ongoing though :)
