### ISSUE TITLE
Error occurred when populate the answer store

### ISSUE THREAD

**Issue by wangzhidong** [watson-developer-cloud/questions-with-classifier-ega#58]
When I execute the 
curl -X POST -H "Content-Type: application/json" -d @questions-with-classifier-ega-war/target/classes/answers.json http://btmuwatson.mybluemix.net/api/v1/manage/answer

to populate the answer store, the error happened:

**<div id="error"> Exception thrown by application class 'com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.createSingletonInstance:221'
</div>
<div id="code">
javax.servlet.ServletException: Resource class com.ibm.watson.app.qaclassifier.ClassifierApplicationImpl can not be instantiated due to InvocationTargetException<br>
<div id="stack">at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.createSingletonInstance(LibertyJaxRsServerFactoryBean.java:221)<br>at [internal classes]<br>at com.ibm.watson.app.common.util.rest.CORSFilter.doFilter(CORSFilter.java:39)<br>at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:207)<br>at [internal classes]<br>**

I also tried with following url to populate the answer store, got same error.
http://btmuwatson.mybluemix.net/api/doc/#!/Manage/createAnswer

I deleted the app and redeploy again, always get the same error.

**Comment by wangzhidong** [comment]
After I deployed the questions-with-classifier-ega-war.zip, I was able to see the Popular questions. 
http://btmuwatson.mybluemix.net/
But when I click any one of the Popular questions.  
"It displays I am currently taking a break to do some reading.
Please try again soon."

The log shows:
14:18:31.837 [Default Executor-thread-74] ERROR com.ibm.watson.app.qaclassifier.rest.impl.ConversationApiImpl - AQWQAC14003E - There are no available classifiers

**Comment by tdalbo92** [comment]
It looks like you need to verify a classifier has been bound to the application in Bluemix, and make sure it's been trained.  Then restart the app and let me know if you still have issues.

**Comment by wangzhidong** [comment]
Could you please give a detail steps on how to verify a classifier has been bound to application in Bluemix, thanks so much.

**Comment by tdalbo92** [comment]
You can follow the steps here in the Bluemix documentation: https://www.ng.bluemix.net/docs/services/reqnsi.html#req_instance

You've trained an NLClassifier instance, right?

**Comment by wangzhidong** [comment]
I didn't take any action, but toady it working fine. Is that means after training, need a period of time to take effective?
BTW, is there a way to test on local environment?

**Comment by tdalbo92** [comment]
Yes!  If you run this command, it will get you a local server running at whichever port you want:
`mvn pre-integration-test -DskipTests -Dliberty.http.port=9080`

That will start the local liberty server with all the proper settings.  You can see the console logs in `/questions-with-classifier-ega-test/target/liberty/wlp/usr/servers/defaultServer/logs`, and can stop the server by executing `mvn liberty:stop-server` from the `questions-with-classifier-ega-test` directory.
