### ISSUE TITLE
mvn install err in stage 1

### ISSUE THREAD

**Issue by ChristiaL** [watson-developer-cloud/questions-with-classifier-ega#59]
When I run "mvn install" after I have cloned the questions-with-classifier-ega repository, I have config the proxy of maven but it shows the errors as below.
I'm a newcomer to java and I have searched a lot but got no answers.
Could you give me some suggestions or ideas?
Thank you very much!
![image](https://cloud.githubusercontent.com/assets/17028328/12755642/42beb3a2-ca0b-11e5-8031-98440016d285.png)

**Comment by tdalbo92** [comment]
It looks like there's an issue with Bower's upstream sources, causing its connections to timeout.  

What are the extent of your proxies?

**Comment by tdalbo92** [comment]
@ChristiaL  Give it another try now - I bet it was just a weird issue with Bower's servers.

**Comment by ChristiaL** [comment]
I just set some code in settings.xml as bellow, which in the file of maven. Is this a right format?
![image](https://cloud.githubusercontent.com/assets/17028328/12770016/c3b7b78c-ca57-11e5-893b-278fd408564d.png)

**Comment by tdalbo92** [comment]
I know we haven't tested it with proxies, so I can't say for sure whether or not this is the cause. 

You still can't get `mvn install` to pass the `bower install` section?

**Comment by tdalbo92** [comment]
It looks like the proxy very well could be the cause of this problem.  I can't replicate your error so I can't guarantee a fix, but I'd try looking here to see if any of these answers help.   You should be able to make a .bowerrc file in the questions-with-classifier-ega-war/ folder and configure your proxy settings accordingly.

http://stackoverflow.com/questions/21750804/bower-calls-blocked-by-corporate-proxy
