### ISSUE TITLE
When try to populate Japanese answer store, got 500 error, but English answer is ok

### ISSUE THREAD

**Issue by wangzhidong** [watson-developer-cloud/questions-with-classifier-ega#60]
**answers:**
[
  {
  	questionText: "投資信託にはどのような種類がありますか？",
  	className: "10889_fund_type"
  },
  {
  	questionText: "外貨MMFの購入・解約時の為替相場を教えてください。",
  	className: "10913_mmf_ex_rate"
  },
  {
  	questionText: "外貨MMFの取扱時間を教えてください。",
  	className: "10911_mmf_sev_time"
  },
  {
  	questionText: "投資信託はATMで取引することはできますか？",
  	className: "10893_fund_atm"
  },
  {
  	questionText: "投資信託を売却すると、売却代金はいつ受け取りできますか？",
  	className: "10891_fund_cash"
  }
]

**error:**
<div id="error"> Exception thrown by application class 'org.apache.wink.server.internal.RequestProcessor.handleRequest:195'
</div>
<div id="code">
javax.servlet.ServletException: com.fasterxml.jackson.databind.JsonMappingException: Unexpected character &#40;&#39;q&#39; &#40;code 113&#41;&#41;: was expecting double-quote to start field name
 at [Source: com.ibm.ws.webcontainer.srt.SRTInputStream@99c223d0&#59; line: 3, column: 5] &#40;through reference chain: java.util.ArrayList[0]&#41;<br>
<div id="stack">at org.apache.wink.server.internal.RequestProcessor.handleRequest(RequestProcessor.java:195)<br>at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:107)<br>at [internal classes]<br>at com.ibm.watson.app.common.util.rest.CORSFilter.doFilter(CORSFilter.java:39)<br>at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:207)<br>at [internal classes]<br>
</div>Caused by: 
com.fasterxml.jackson.databind.JsonMappingException: Unexpected character &#40;&#39;q&#39; &#40;code 113&#41;&#41;: was expecting double-quote to start field name
 at [Source: com.ibm.ws.webcontainer.srt.SRTInputStream@99c223d0&#59; line: 3, column: 5] &#40;through reference chain: java.util.ArrayList[0]&#41;<br>
<div id="stack">at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)<br>at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:189)<br>at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)<br>at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:206)<br>at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)<br>at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1232)<br>at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:676)<br>at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:808)<br>at org.apache.wink.server.internal.registry.ServerInjectableFactory$EntityParam.getValue(ServerInjectableFactory.java:198)<br>at org.apache.wink.common.internal.registry.InjectableFactory.instantiate(InjectableFactory.java:68)<br>at org.apache.wink.server.internal.handlers.CreateInvocationParametersHandler.handleRequest(CreateInvocationParametersHandler.java:44)<br>at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)<br>at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)<br>at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)<br>at org.apache.wink.server.handlers.AbstractHandler.handleRequest(AbstractHandler.java:34)<br>at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)<br>at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)<br>at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)<br>at org.apache.wink.server.internal.handlers.FindResourceMethodHandler.handleSubResourceMethod(FindResourceMethodHandler.java:188)<br>at org.apache.wink.server.internal.handlers.FindResourceMethodHandler.handleRequest(FindResourceMethodHandler.java:110)<br>at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)<br>at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)<br>at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)<br>at org.apache.wink.server.internal.handlers.FindRootResourceHandler.handleRequest(FindRootResourceHandler.java:95)<br>at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)<br>at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)<br>at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)<br>at org.apache.wink.server.internal.handlers.HeadMethodHandler.handleRequest(HeadMethodHandler.java:53)<br>at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)<br>at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)<br>at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)<br>at org.apache.wink.server.internal.handlers.OptionsMethodWADLHandler.handleRequest(OptionsMethodWADLHandler.java:51)<br>at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)<br>at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)<br>at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)<br>at org.apache.wink.server.internal.handlers.SearchResultHandler.handleRequest(SearchResultHandler.java:33)<br>at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)<br>at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)<br>at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)<br>at org.apache.wink.server.internal.log.ResourceInvocation.handleRequest(ResourceInvocation.java:92)<br>at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)<br>at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)<br>at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)<br>at org.apache.wink.server.internal.log.Requests.handleRequest(Requests.java:76)<br>at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)<br>at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)<br>at org.apache.wink.server.handlers.AbstractHandlersChain.doChain(AbstractHandlersChain.java:75)<br>at org.apache.wink.server.handlers.AbstractHandlersChain.run(AbstractHandlersChain.java:60)<br>at org.apache.wink.server.internal.RequestProcessor.handleRequestWithoutFaultBarrier(RequestProcessor.java:207)<br>at org.apache.wink.server.internal.RequestProcessor.handleRequest(RequestProcessor.java:154)<br>... 5 more<br>
</div>Caused by: 
com.fasterxml.jackson.core.JsonParseException: Unexpected character &#40;&#39;q&#39; &#40;code 113&#41;&#41;: was expecting double-quote to start field name
 at [Source: com.ibm.ws.webcontainer.srt.SRTInputStream@99c223d0&#59; line: 3, column: 5]<br>
<div id="stack">at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)<br>at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)<br>at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:437)<br>at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleOddName(UTF8StreamJsonParser.java:1799)<br>at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parseName(UTF8StreamJsonParser.java:1496)<br>at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:693)<br>at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)<br>at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:232)<br>... 52 more<br>
</div>

**Comment by bsfarrell** [comment]
That's not valid json- field names (questionText, className) need to be enclosed in double-quotes.

**Comment by tdalbo92** [comment]
Here's a useful tool to help with JSON validation

http://jsonlint.com/

**Comment by wangzhidong** [comment]
Thank you Tom, sorry that I used a wrong json file.
