### ISSUE TITLE
Do we have any guide to debug this application on local environment?

### ISSUE THREAD

**Issue by wangzhidong** [watson-developer-cloud/questions-with-classifier-ega#63]

**Comment by tdalbo92** [comment]
It's a bit tricky - when using maven to deploy the application locally, I don't have a workflow for debugging the app.  Alternatively you can deploy the app using the Bluemix Liberty tools in Eclipse https://marketplace.eclipse.org/content/ibm-eclipse-tools-bluemix.  This will require you to configure your own web.xml, server.env and server.xml.  You can use the versions we have checked into the repo as a reference, although a few specifics might need to be changed (like where the app directory is).

Lastly, the maven liberty plugin opens a port so you can attach the Eclipse Remote Debugger.  I haven't tried this yet, but it might be a good solution for easy deployment and easy debugging.

**Comment by tdalbo92** [comment]
In terms of debugging the UI - you can just use your favorite browser's debugging tools.  

Hope this helps!  Best of luck!
