### ISSUE TITLE
When run the mvn install only for framework-ega-infra project, get error in attached file, could you please advise?

### ISSUE THREAD

**Issue by wangzhidong** [watson-developer-cloud/questions-with-classifier-ega#64]
[error.txt.zip](https://github.com/watson-developer-cloud/questions-with-classifier-ega/files/144716/error.txt.zip)
[Uploading error.txt.zip…]()
[Uploading error.txt.zip…]()

**Comment by tdalbo92** [comment]
@wangzhidong It looks like you've modified the questions.csv file.  Is that true?

**Comment by wangzhidong** [comment]
No, I didn't modify anything

**Comment by tdalbo92** [comment]
You don't need to run `mvn install` on the framework-ega-infra project, just run it on the root /framework-ega project.

I just noticed that you were running it on a particular sub-project and I can replicate the error you're seeing too.
