### ISSUE TITLE
SQL Database instructions incorrect

### ISSUE THREAD

**Issue by louiscremen** [watson-developer-cloud/questions-with-classifier-ega#66]
Hey guys,

Newbie here. Following the readme. There does not appear to be a SQL Database service offered as stated in point 4. There is a PostgreSQL service by Compose. (I'm still working through the tutorial, so I am unsure whether this is sufficient. I will soon find out).

This is the part in the README that I am referring to:

> Add SQL database service to your app. To use an instance of the service that is bound to another app, skip this step.
> Click ADD A SERVICE OR API.
> Select the Data Management category, and _select the SQL Database service._
> Ensure that your app is specified in the App dropdown.
> In the Service name field, type a unique name for your service, such as qaclassifier-sample-db.
> Click CREATE. The Restage Application window is displayed.
> Click RESTAGE to restage your app.

**Comment by tdalbo92** [comment]
In the same section on the Bluemix dashboard, you'll be able to see a service named "SQL Database".  The tile looks like this: 
![image](https://cloud.githubusercontent.com/assets/8292003/13603039/64be0d3c-e508-11e5-8859-f09f3825ca59.png)

Let me know if you continue to have trouble finding it.  I just verified - it's there, but I agree it can be overwhelming sifting through the dozens of tiles.

**Comment by tdalbo92** [comment]
Also - I do not think the PostgreSQL service will be sufficient.  We've only developed, tested, and recommended using this service.  It also have a free plan with 100MB which will be plenty for the sample data we provide.

**Comment by louiscremen** [comment]
Right. I see what happened. SQL Database is a service on your US South servers, but not on your Sydney servers.

I'll redo my app on the US South account then.

The category is Data and Analytics - rather than Data Management. 

Thank you for your time :)

**Comment by tdalbo92** [comment]
Oh I didn't even realize there was a discrepancy between services offered at the different data centers!!

Sorry for the inconvenience!
