### ISSUE TITLE
pox.xml bug on Java8

### ISSUE THREAD

**Issue by louiscremen** [watson-developer-cloud/questions-with-classifier-ega#67]
After a few hours of trying to get mvn install to work for the questions-with-classifier-ega, maven continuously gave me an error:

> java.lang.VerifyError: Bad <init> method call from inside of a branch
> Exception Details:
>   Location:
>     com/ibm/watson/app/qaclassifier/rest/impl/StatusApiImplTest.<init>()V @32: invokespecial
>   Reason:
>     Error exists in the bytecode

I fixed this by modifying the pox.xml in the root directory to add -noverify to maven-surefire-plugin. Everything successfully installed for me after that:
```
<plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.18.1</version>
        <configuration>
          <redirectTestOutputToFile>true</redirectTestOutputToFile>
          <argLine>-noverify</argLine> <!-- This is required for certain versions of Java8 -->
        </configuration>
      </plugin>
```

Hope this saves people the hours that it took me :). 

Source:
http://stackoverflow.com/questions/25428317/bad-init-method-call-from-inside-of-a-branch
http://www-01.ibm.com/support/docview.wss?uid=swg27045639

mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T20:41:47+04:00)
Java version: 1.8.0_11, vendor: Oracle Corporation
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.3", arch: "x86_64", family: "mac"

**Comment by tdalbo92** [comment]
Hey, thanks for figuring that out.  We've only been developing on a 1.7u49 JDK, in which according to your link this bug has been fixed.  It also looks like newer versions of Java 8 also fix this bug. 

Sorry for the inconvenience!!  I'll add a note in the wiki about this.
