### ISSUE TITLE
How to solve Maven dependency issues for Natural Language Classifier service?

### ISSUE THREAD

**Issue by contact2bipin** [watson-developer-cloud/questions-with-classifier-ega#69]
I'm trying out Natural Language Classifier service on bluemix and I'm trying out the given sample, 'questions-with-classifier-ega' using instructions provided here and whenever I'm trying any Maven commands, ( package, install etc..) I'm getting dependency errors such as -

[ERROR] Failed to execute goal on project questions-with-classifier-ega-war: Could not resolve dependencies for project com.ibm.watson.app.gallery:questions-with-classifier-ega-war:war:1.0.2-SNAPSHOT: The following artifacts could not be resolved: com.ibm.watson.app.gallery:framework-ega-infra:jar:1.0.2-SNAPSHOT, com.ibm.watson.app.gallery:framework-ega-infra:jar:tests:1.0.2-SNAPSHOT: Could not find artifact com.ibm.watson.app.gallery:framework-ega-infra:jar:1.0.2-SNAPSHOT ->

Also there are errors related to setting up Liberty profiles even for setting up Dialog service.

So I bypassed this step, used readily available answer.json file to upload it to bluemix but when I user CURL POST command to upload it, I'm getting following error

HTTP Status 403 - Access to the requested resource has been denied
type Status report

message Access to the requested resource has been denied

description Access to the specified resource has been forbidden.

**Comment by tdalbo92** [comment]
Please revisit the instructions and make sure you follow them down to every last step.

The first issue you have is that you need to first clone the [framework-ega repo](https://github.com/watson-developer-cloud/framework-ega) and run `mvn install`

This application does not use the Dialog service at all, only the Natural Language Classifier. 

Lastly, answer.json is used to populate the answer store database.  If `mvn install` isn't working for you, then you won't be building a .zip to push to Bluemix, and won't have a database to populate.  If you're trying to train the classifier, you'll want to use questions.csv as the training.  The proper `curl` command is in the README.
