### ISSUE TITLE
mvn install failed

### ISSUE THREAD

**Issue by albhardy** [watson-developer-cloud/questions-with-classifier-ega#70]
I can't get  `mvn install` running in Step 4 in Cloning and building the project yourself (Error message: `'npm install --color=false' failed`). There seems to be issues with [new directory config](https://github.com/eirslett/frontend-maven-plugin/issues/328) for node v0.12.2 and npm v2.7.6. Current workaround is to update pom.xml to

```
     <groupId>com.github.eirslett</groupId>
        <artifactId>frontend-maven-plugin</artifactId>
        <version>0.0.27</version>
        <!-- add optional <configuration> here -->
        <executions>
          <execution>
            <id>install node and npm</id>
            <goals>
              <goal>install-node-and-npm</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <nodeVersion>v0.12.2</nodeVersion>
              <npmVersion>2.7.4</npmVersion>
            </configuration>
          </execution>
```

**Comment by tdalbo92** [comment]
If you'd like, feel free to open a Pull Request with this updated pom and I'll make sure it gets merged.

It looks like the fix might also be made upstream in the maven frontend plugin, but a nice shim like this in the meantime might be good.
