### ISSUE TITLE
Generating my own training and answers JSON files

### ISSUE THREAD

**Issue by louiscremen** [watson-developer-cloud/questions-with-classifier-ega#72]
Apologies for the newbie question.

I am following point 4 here:
https://github.com/watson-developer-cloud/questions-with-classifier-ega#prepare-your-own-data-for-training-the-classifier-and-populating-the-answer-store

I have attempted several different variations on this command (including -cp .), 
`java com.ibm.watson.app.qaclassifier.tools.GenerateTrainingAndPopulationData
`
but each time I receive this error:
> Error: Could not find or load main class com.ibm.watson.app.qaclassifier.tools.GenerateTrainingAndPopulationData

I have run the command in a few directories including questions-with-classifier-ega-war/src/main/java/com/ibm/watson/app/qaclassifier/tools

**Comment by tdalbo92** [comment]
Have you figured this out?  

If you replace the data in our default directories, you'll also get this generated file for free during Maven's `prepare-package` phase.  Here's the relevant pom.xml snippet in the -war project:

```xml
          <execution>
            <id>generate-training-and-answers-json</id>
            <!-- Might make more sense in generate-resources, but we have to wait for the class to be compiled. -->
            <phase>prepare-package</phase>
            <goals>
              <goal>java</goal>
            </goals>
            <configuration>
              <mainClass>com.ibm.watson.app.qaclassifier.tools.GenerateTrainingAndPopulationData</mainClass>
              <arguments>
                <argument>--questionInput</argument>
                <argument>${project.basedir}/src/main/resources/questions.csv</argument>
                <argument>--questionOutput</argument>
                <argument>${project.basedir}/src/main/resources/training.json</argument>
                <argument>--answerInput</argument>
                <argument>${project.basedir}/src/main/resources/answers.csv</argument>
                <argument>--answerTextDirectory</argument>
                <argument>${project.basedir}/src/main/resources/answers</argument>
                <argument>--answerOutput</argument>
                <argument>${project.build.outputDirectory}/answers.json</argument>
              </arguments>
            </configuration>
          </execution>
```

**Comment by louiscremen** [comment]
I did not figure this out, so I wrote a json writer in python. This worked great for the training data and I've been using the excellent "natural-language-classifier-toolkit" to help train the data, but I have not yet worked out the answers.json. I have manually encoded the \u003c \u003d and \u003e (< > =) characters to match the format provided in the example answers.json file, but I am getting a error which was a 'help-wanted' in a different question.  I am currently working through this problem.

> javax.servlet.ServletException: Resource class com.ibm.watson.app.qaclassifier.ClassifierApplicationImpl can not be instantiated due to InvocationTargetException

The solution of using mvn prepare-package did not work because it depends on the answers.json file existing in order for it to work

> [WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireFilesExist failed with message:
> The generated directory containing the classes from Swagger must be present
> Some required files are missing:
> <lpath>/questions-with-classifier-ega/questions-with-classifier-ega-war/target/generated-sources/src/main/java

I will comment in that issue if I cannot figure it out. However, I would like to share the sentiment the other developer showed which is that your response times are awesome and you are amazingly helpful. Thank you.

**Comment by cama** [comment]
I receive the same error.  @tdalbo92 Are you implying instead of running GenerateTrainingAndPopulationData we can manipulate pom.xml? If so, how does the new training.json get generated to train and populate answers?

**Comment by tdalbo92** [comment]
Could you refresh my memory?  This was opened so long ago, I don't quite remember the details of what was trying to be done, and the problem that arose. 

What are the steps you're taking?

**Comment by cama** [comment]
I've completed all the steps successfully and now want to prepare my own data. 

As per the beginning of the original thread I'm trying to run a java command in step " https://github.com/watson-developer-cloud/questions-with-classifier-ega#prepare-your-own-data-for-training-the-classifier-and-populating-the-answer-store"

I'm on OSX and have set the env path to the top level package and ran the command from the top level package (java/com/ibm/watson/app/qaclassifier/tools/)

I followed this solution with no luck - http://stackoverflow.com/questions/24174947/mac-terminal-could-not-find-or-load-main-class-classname

Hope this helps

**Comment by cama** [comment]
@tdalbo92 It seems the java app run through the command line hasn't been compiled into a .class or .jar file.

**Comment by tdalbo92** [comment]
I suppose I'm still a little confused why the built-in `mvn` command isn't working for generating this file.

**Comment by cama** [comment]
The test throws an error here when MVN Install is run in the Framework-ega folder.

`-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.ibm.watson.app.common.services.box.impl.BoxServiceTest
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.635 sec
Running com.ibm.watson.app.common.services.impl.BluemixServicesBinderTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.033 sec
Running com.ibm.watson.app.common.services.nlclassifier.impl.NLClassifierServiceTest
15:22:17.867 [main] ERROR com.ibm.watson.app.common.util.rest.JSONResponseHandler - AQWEGA04001E - Unable to parse JSON: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING
15:22:17.869 [main] ERROR com.ibm.watson.app.common.util.rest.JSONResponseHandler - catching
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING
	at com.google.gson.Gson.fromJson(Gson.java:815) ~[gson-2.2.4.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:868) ~[gson-2.2.4.jar:?]
`
