### ISSUE TITLE
Run mvn install in the root of the questions-with-classifier-ega repository Error

### ISSUE THREAD

**Issue by cama** [watson-developer-cloud/questions-with-classifier-ega#77]
When I Stage 1. Step 4 -  "Run mvn install in the root of the questions-with-classifier-ega repository to build and install the components to your local Maven repository."

I receive the following error:

```
[ERROR] Failed to execute goal on project questions-with-classifier-ega-war: Could not resolve dependencies for project com.ibm.watson.app.gallery:questions-with-classifier-ega-war:war:1.0.2-SNAPSHOT: The following artifacts could not be resolved: com.ibm.watson.app.gallery:framework-ega-infra:jar:1.0.2-SNAPSHOT, com.ibm.watson.app.gallery:framework-ega-infra:jar:tests:1.0.2-SNAPSHOT, com.ibm.watson.app.gallery:framework-ega-test:jar:1.0.2-SNAPSHOT: Could not find artifact com.ibm.watson.app.gallery:framework-ega-infra:jar:1.0.2-SNAPSHOT -> [Help 1]
[ERROR] 
```

If I run sudo mvn install

```
[INFO] Running 'bower install' in /Users/cmcgrane/Documents/bluemix/questions-with-classifier-ega/questions-with-classifier-ega-war
[ERROR] bower ESUDO         Cannot be run with sudo
[ERROR] 
[ERROR] Additional error details:
[ERROR] Since bower is a user command, there is no need to execute it with superuser permissions.
[ERROR] If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.
```

I can run  `bower install` within questions-with-classifier-ega-war

But I have no way to integrate it into the script.

I'm using OSX

Any ideas?

Thanks

**Comment by cama** [comment]
Noticed an error occurs immediately before the bower error.
```
[INFO] Running 'npm install --color=false' in /Users/cmcgrane/Desktop/bluemix/questions-with-classifier-ega/questions-with-classifier-ega-war
[ERROR] npm WARN package.json karma-phantomjs-launcher@0.1.4 No README data
[INFO] 
```

**Comment by tdalbo92** [comment]
You shouldn't have to run anything with `sudo`, maven is not meant to be executed with those privileges. 

You need to reference the section in the README about installing the `framework-ega` repository first.  Once that's taken care of, your dependency errors will go away.  

That second [ERROR] you printed shouldn't affect the built at all.  It's just npm being whiny.

**Comment by cama** [comment]
My permissions where I placed the files were screwy. New location and I was able to run with-out sudo. I did have to give write permission bower-github.json. It looks like a common problem with MVN and Bower.
